# Generated by Django 2.0 on 2018-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='utxo_root',
            new_name='output_root',
        ),
        migrations.RemoveField(
            model_name='output',
            name='height',
        ),
        migrations.RemoveField(
            model_name='output',
            name='lock_height',
        ),
        migrations.AddField(
            model_name='output',
            name='merkle_proof',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='proof',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='switch_commit_hash',
            field=models.CharField(max_length=64),
        ),
    ]
