# Generated by Django 2.0 on 2018-03-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20180321_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='switch_commit_hash',
        ),
    ]
