# Generated by Django 2.0 on 2018-03-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_remove_output_switch_commit_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='difficulty',
        ),
    ]
