# Generated by Django 2.0 on 2018-04-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_remove_block_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='total_kernel_offset',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
