# Generated by Django 2.0 on 2018-07-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_block_total_kernel_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='cuckoo_size',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
