# Generated by Django 2.0 on 2018-07-16 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_block_cuckoo_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='block_height',
            field=models.IntegerField(null=True, default=-1),
            preserve_default=False,
        ),
    ]
