# Generated by Django 2.1.2 on 2018-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_output_block_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='cuckoo_size',
            new_name='edge_bits',
        ),
        migrations.AddField(
            model_name='block',
            name='prev_root',
            field=models.CharField(default=29, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='scaling_difficulty',
            field=models.IntegerField(default=29),
            preserve_default=False,
        ),
    ]
