# Generated by Django 2.1.1 on 2018-10-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_auto_20181018_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='scaling_difficulty',
            new_name='secondary_scaling',
        ),
    ]
