# Generated by Django 2.1.1 on 2019-01-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_auto_20181113_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='mmr_index',
            field=models.IntegerField(null=True),
        ),
    ]
