# Generated by Django 2.1.1 on 2019-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0012_output_mmr_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='data',
            field=models.CharField(db_index=True, max_length=66),
        ),
        migrations.AlterField(
            model_name='output',
            name='commit',
            field=models.CharField(db_index=True, max_length=66),
        ),
    ]
