# Generated by Django 2.1.1 on 2019-12-02 15:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0013_auto_20190521_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='cuckoo_solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None),
        ),
    ]
