# Generated by Django 2.1.1 on 2020-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_auto_20200716_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel',
            name='fee_shift',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
